2024-08-07 17:05:30,187 INFO    MainThread:20104 [wandb_setup.py:_flush():68] Configure stats pid to 20104
2024-08-07 17:05:30,187 INFO    MainThread:20104 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Dell\.config\wandb\settings
2024-08-07 17:05:30,187 INFO    MainThread:20104 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Dell\Desktop\DIFUSCO-main\wandb\settings
2024-08-07 17:05:30,188 INFO    MainThread:20104 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2024-08-07 17:05:30,188 INFO    MainThread:20104 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'test.py', 'program': 'C:/Users/Dell/Desktop/DIFUSCO-main/test.py'}
2024-08-07 17:05:30,188 INFO    MainThread:20104 [wandb_init.py:_log_setup():478] Logging user logs to C:\Users\Dell\Desktop\DIFUSCO-main\wandb\run-20240807_170530-al5wqm2c\logs\debug.log
2024-08-07 17:05:30,188 INFO    MainThread:20104 [wandb_init.py:_log_setup():479] Logging internal logs to C:\Users\Dell\Desktop\DIFUSCO-main\wandb\run-20240807_170530-al5wqm2c\logs\debug-internal.log
2024-08-07 17:05:30,189 INFO    MainThread:20104 [wandb_init.py:init():518] calling init triggers
2024-08-07 17:05:30,189 INFO    MainThread:20104 [wandb_init.py:init():522] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'architecture': 'MLP', 'dataset': 'MNIST', 'epochs': 30}
2024-08-07 17:05:30,189 INFO    MainThread:20104 [wandb_init.py:init():571] starting backend
2024-08-07 17:05:30,189 INFO    MainThread:20104 [wandb_init.py:init():575] setting up manager
2024-08-07 17:05:30,193 INFO    MainThread:20104 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=spawn, using: spawn
2024-08-07 17:05:30,198 INFO    MainThread:20104 [wandb_init.py:init():582] backend started and connected
2024-08-07 17:05:30,203 INFO    MainThread:20104 [wandb_init.py:init():670] updated telemetry
2024-08-07 17:05:30,204 INFO    MainThread:20104 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2024-08-07 17:05:34,440 WARNING MsgRouterThr:20104 [router.py:message_loop():77] message_loop has been closed
2024-08-07 17:05:35,358 ERROR   MainThread:20104 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "E:\Program Files (x86)\anaconda\envs\DIFUSCO\lib\site-packages\wandb\sdk\wandb_init.py", line 1108, in init
    run = wi.init()
  File "E:\Program Files (x86)\anaconda\envs\DIFUSCO\lib\site-packages\wandb\sdk\wandb_init.py", line 716, in init
    cancel=True,
  File "E:\Program Files (x86)\anaconda\envs\DIFUSCO\lib\site-packages\wandb\sdk\lib\mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
